name = "Momo's Survival 1.7.10"
author = "chubbymomo"
version = "1.0.0"
description = "A custom 1.7.10 survival modpack."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4fb2089b8b3e796ab0502de43f053cdb5b73dd11dd8ec8d6288f2af062080260"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
