name = "Momo's Survival 1.7.10"
author = "chubbymomo"
version = "1.0.0"
description = "A custom 1.7.10 survival modpack."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b52b7eebe19422f425f746f07752020a65086b6afe40e256443d179e5b8648c"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
