name = "Momo's Survival 1.7.10"
author = "chubbymomo"
version = "1.0.0"
description = "A custom 1.7.10 survival modpack."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b5137f17a900f1081663a44727c85fe014d414054e3f764e51ded9df985bc27"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
